import type { INodeProperties } from 'n8n-workflow';

export const courseOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['course'],
			},
		},
		options: [
			{
				name: 'Conclude',
				value: 'conclude',
				description: 'Conclude a course',
				action: 'Conclude a course',
			},
			{
				name: 'Copy',
				value: 'copy',
				description: 'Copy a course to a new course',
				action: 'Copy a course',
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new course',
				action: 'Create a course',
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete a course',
				action: 'Delete a course',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get a single course',
				action: 'Get a course',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many courses',
				action: 'Get many courses',
			},
			{
				name: 'List Students',
				value: 'listStudents',
				description: 'List students enrolled in a course',
				action: 'List students in a course',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update a course',
				action: 'Update a course',
			},
		],
		default: 'getAll',
	},
];

export const courseFields: INodeProperties[] = [
	// ----------------------------------
	//         course: shared
	// ----------------------------------
	{
		displayName: 'Course ID',
		name: 'courseId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['get', 'update', 'delete', 'conclude', 'copy', 'listStudents'],
			},
		},
		description: 'The ID of the course',
	},

	// ----------------------------------
	//         course: create
	// ----------------------------------
	{
		displayName: 'Account ID',
		name: 'accountId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['create'],
			},
		},
		description: 'The ID of the account to create the course in',
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['create'],
			},
		},
		description: 'The name of the course',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Allow Student Assignment Edits',
				name: 'allow_student_assignment_edits',
				type: 'boolean',
				default: false,
				description: 'Whether students can edit their own assignments',
			},
			{
				displayName: 'Allow Student Forum Attachments',
				name: 'allow_student_forum_attachments',
				type: 'boolean',
				default: false,
				description: 'Whether students can attach files to discussion posts',
			},
			{
				displayName: 'Allow Wiki Comments',
				name: 'allow_wiki_comments',
				type: 'boolean',
				default: false,
				description: 'Whether students can comment on wiki pages',
			},
			{
				displayName: 'Apply Assignment Group Weights',
				name: 'apply_assignment_group_weights',
				type: 'boolean',
				default: false,
				description: 'Whether to weight final grade based on assignment groups',
			},
			{
				displayName: 'Course Code',
				name: 'course_code',
				type: 'string',
				default: '',
				description: 'The course code (short name)',
			},
			{
				displayName: 'Course Format',
				name: 'course_format',
				type: 'options',
				options: [
					{ name: 'Blended', value: 'blended' },
					{ name: 'On Campus', value: 'on_campus' },
					{ name: 'Online', value: 'online' },
				],
				default: 'online',
				description: 'The format of the course',
			},
			{
				displayName: 'Default View',
				name: 'default_view',
				type: 'options',
				options: [
					{ name: 'Assignments', value: 'assignments' },
					{ name: 'Feed', value: 'feed' },
					{ name: 'Modules', value: 'modules' },
					{ name: 'Syllabus', value: 'syllabus' },
					{ name: 'Wiki', value: 'wiki' },
				],
				default: 'modules',
				description: 'The default view for the course home page',
			},
			{
				displayName: 'Enable SIS Reactivation',
				name: 'enable_sis_reactivation',
				type: 'boolean',
				default: false,
				description: 'Whether to enable SIS reactivation for the course',
			},
			{
				displayName: 'End At',
				name: 'end_at',
				type: 'dateTime',
				default: '',
				description: 'Course end date in ISO 8601 format',
			},
			{
				displayName: 'Enrollment Term ID',
				name: 'enrollment_term_id',
				type: 'string',
				default: '',
				description: 'The ID of the enrollment term for the course',
			},
			{
				displayName: 'Grade Passback Setting',
				name: 'grade_passback_setting',
				type: 'options',
				options: [
					{ name: 'Disabled', value: 'disabled' },
					{ name: 'Nightly Sync', value: 'nightly_sync' },
					{ name: 'Not Set', value: 'not_set' },
				],
				default: 'not_set',
				description: 'Grade passback setting for the course',
			},
			{
				displayName: 'Grading Standard ID',
				name: 'grading_standard_id',
				type: 'string',
				default: '',
				description: 'The ID of the grading standard to use',
			},
			{
				displayName: 'Hide Final Grades',
				name: 'hide_final_grades',
				type: 'boolean',
				default: false,
				description: 'Whether to hide final grades from students',
			},
			{
				displayName: 'Integration ID',
				name: 'integration_id',
				type: 'string',
				default: '',
				description: 'The integration ID for the course',
			},
			{
				displayName: 'Is Public',
				name: 'is_public',
				type: 'boolean',
				default: false,
				description: 'Whether the course is publicly visible',
			},
			{
				displayName: 'Is Public to Auth Users',
				name: 'is_public_to_auth_users',
				type: 'boolean',
				default: false,
				description: 'Whether the course is visible to authenticated users',
			},
			{
				displayName: 'License',
				name: 'license',
				type: 'options',
				options: [
					{ name: 'CC Attribution', value: 'cc_by' },
					{ name: 'CC Attribution No Derivatives', value: 'cc_by_nd' },
					{ name: 'CC Attribution Non-Commercial', value: 'cc_by_nc' },
					{ name: 'CC Attribution Non-Commercial No Derivatives', value: 'cc_by_nc_nd' },
					{ name: 'CC Attribution Non-Commercial Share Alike', value: 'cc_by_nc_sa' },
					{ name: 'CC Attribution Share Alike', value: 'cc_by_sa' },
					{ name: 'Private (Copyrighted)', value: 'private' },
					{ name: 'Public Domain', value: 'public_domain' },
				],
				default: 'private',
				description: 'The license for course content',
			},
			{
				displayName: 'Offer',
				name: 'offer',
				type: 'boolean',
				default: false,
				description: 'Whether to make the course available to students immediately',
			},
			{
				displayName: 'Open Enrollment',
				name: 'open_enrollment',
				type: 'boolean',
				default: false,
				description: 'Whether to allow self-enrollment',
			},
			{
				displayName: 'Public Description',
				name: 'public_description',
				type: 'string',
				typeOptions: {
					rows: 4,
				},
				default: '',
				description: 'A publicly visible description of the course',
			},
			{
				displayName: 'Public Syllabus',
				name: 'public_syllabus',
				type: 'boolean',
				default: false,
				description: 'Whether to make the syllabus publicly visible',
			},
			{
				displayName: 'Public Syllabus to Auth',
				name: 'public_syllabus_to_auth',
				type: 'boolean',
				default: false,
				description: 'Whether to make the syllabus visible to authenticated users',
			},
			{
				displayName: 'Restrict Enrollments to Course Dates',
				name: 'restrict_enrollments_to_course_dates',
				type: 'boolean',
				default: false,
				description: 'Whether students can only access during course dates',
			},
			{
				displayName: 'Self Enrollment',
				name: 'self_enrollment',
				type: 'boolean',
				default: false,
				description: 'Whether to allow self-enrollment',
			},
			{
				displayName: 'SIS Course ID',
				name: 'sis_course_id',
				type: 'string',
				default: '',
				description: 'The SIS ID for the course',
			},
			{
				displayName: 'Start At',
				name: 'start_at',
				type: 'dateTime',
				default: '',
				description: 'Course start date in ISO 8601 format',
			},
			{
				displayName: 'Syllabus Body',
				name: 'syllabus_body',
				type: 'string',
				typeOptions: {
					rows: 4,
				},
				default: '',
				description: 'The syllabus content (supports HTML)',
			},
			{
				displayName: 'Term ID',
				name: 'term_id',
				type: 'string',
				default: '',
				description: 'The term ID for the course',
			},
			{
				displayName: 'Time Zone',
				name: 'time_zone',
				type: 'string',
				default: '',
				description: 'The time zone for the course (e.g., "America/New_York")',
			},
		],
	},

	// ----------------------------------
	//         course: update
	// ----------------------------------
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Allow Student Assignment Edits',
				name: 'allow_student_assignment_edits',
				type: 'boolean',
				default: false,
				description: 'Whether students can edit their own assignments',
			},
			{
				displayName: 'Allow Student Forum Attachments',
				name: 'allow_student_forum_attachments',
				type: 'boolean',
				default: false,
				description: 'Whether students can attach files to discussion posts',
			},
			{
				displayName: 'Allow Wiki Comments',
				name: 'allow_wiki_comments',
				type: 'boolean',
				default: false,
				description: 'Whether students can comment on wiki pages',
			},
			{
				displayName: 'Apply Assignment Group Weights',
				name: 'apply_assignment_group_weights',
				type: 'boolean',
				default: false,
				description: 'Whether to weight final grade based on assignment groups',
			},
			{
				displayName: 'Course Code',
				name: 'course_code',
				type: 'string',
				default: '',
				description: 'The course code (short name)',
			},
			{
				displayName: 'Course Format',
				name: 'course_format',
				type: 'options',
				options: [
					{ name: 'Blended', value: 'blended' },
					{ name: 'On Campus', value: 'on_campus' },
					{ name: 'Online', value: 'online' },
				],
				default: 'online',
				description: 'The format of the course',
			},
			{
				displayName: 'Default View',
				name: 'default_view',
				type: 'options',
				options: [
					{ name: 'Assignments', value: 'assignments' },
					{ name: 'Feed', value: 'feed' },
					{ name: 'Modules', value: 'modules' },
					{ name: 'Syllabus', value: 'syllabus' },
					{ name: 'Wiki', value: 'wiki' },
				],
				default: 'modules',
				description: 'The default view for the course home page',
			},
			{
				displayName: 'End At',
				name: 'end_at',
				type: 'dateTime',
				default: '',
				description: 'Course end date in ISO 8601 format',
			},
			{
				displayName: 'Enrollment Term ID',
				name: 'enrollment_term_id',
				type: 'string',
				default: '',
				description: 'The ID of the enrollment term for the course',
			},
			{
				displayName: 'Event',
				name: 'event',
				type: 'options',
				options: [
					{ name: 'Claim', value: 'claim' },
					{ name: 'Conclude', value: 'conclude' },
					{ name: 'Delete', value: 'delete' },
					{ name: 'Offer', value: 'offer' },
					{ name: 'Undelete', value: 'undelete' },
				],
				default: 'offer',
				description: 'The action to take on the course',
			},
			{
				displayName: 'Grade Passback Setting',
				name: 'grade_passback_setting',
				type: 'options',
				options: [
					{ name: 'Disabled', value: 'disabled' },
					{ name: 'Nightly Sync', value: 'nightly_sync' },
					{ name: 'Not Set', value: 'not_set' },
				],
				default: 'not_set',
				description: 'Grade passback setting for the course',
			},
			{
				displayName: 'Grading Standard ID',
				name: 'grading_standard_id',
				type: 'string',
				default: '',
				description: 'The ID of the grading standard to use',
			},
			{
				displayName: 'Hide Final Grades',
				name: 'hide_final_grades',
				type: 'boolean',
				default: false,
				description: 'Whether to hide final grades from students',
			},
			{
				displayName: 'Integration ID',
				name: 'integration_id',
				type: 'string',
				default: '',
				description: 'The integration ID for the course',
			},
			{
				displayName: 'Is Public',
				name: 'is_public',
				type: 'boolean',
				default: false,
				description: 'Whether the course is publicly visible',
			},
			{
				displayName: 'Is Public to Auth Users',
				name: 'is_public_to_auth_users',
				type: 'boolean',
				default: false,
				description: 'Whether the course is visible to authenticated users',
			},
			{
				displayName: 'License',
				name: 'license',
				type: 'options',
				options: [
					{ name: 'CC Attribution', value: 'cc_by' },
					{ name: 'CC Attribution No Derivatives', value: 'cc_by_nd' },
					{ name: 'CC Attribution Non-Commercial', value: 'cc_by_nc' },
					{ name: 'CC Attribution Non-Commercial No Derivatives', value: 'cc_by_nc_nd' },
					{ name: 'CC Attribution Non-Commercial Share Alike', value: 'cc_by_nc_sa' },
					{ name: 'CC Attribution Share Alike', value: 'cc_by_sa' },
					{ name: 'Private (Copyrighted)', value: 'private' },
					{ name: 'Public Domain', value: 'public_domain' },
				],
				default: 'private',
				description: 'The license for course content',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'The name of the course',
			},
			{
				displayName: 'Open Enrollment',
				name: 'open_enrollment',
				type: 'boolean',
				default: false,
				description: 'Whether to allow self-enrollment',
			},
			{
				displayName: 'Public Description',
				name: 'public_description',
				type: 'string',
				typeOptions: {
					rows: 4,
				},
				default: '',
				description: 'A publicly visible description of the course',
			},
			{
				displayName: 'Public Syllabus',
				name: 'public_syllabus',
				type: 'boolean',
				default: false,
				description: 'Whether to make the syllabus publicly visible',
			},
			{
				displayName: 'Public Syllabus to Auth',
				name: 'public_syllabus_to_auth',
				type: 'boolean',
				default: false,
				description: 'Whether to make the syllabus visible to authenticated users',
			},
			{
				displayName: 'Restrict Enrollments to Course Dates',
				name: 'restrict_enrollments_to_course_dates',
				type: 'boolean',
				default: false,
				description: 'Whether students can only access during course dates',
			},
			{
				displayName: 'Self Enrollment',
				name: 'self_enrollment',
				type: 'boolean',
				default: false,
				description: 'Whether to allow self-enrollment',
			},
			{
				displayName: 'SIS Course ID',
				name: 'sis_course_id',
				type: 'string',
				default: '',
				description: 'The SIS ID for the course',
			},
			{
				displayName: 'Start At',
				name: 'start_at',
				type: 'dateTime',
				default: '',
				description: 'Course start date in ISO 8601 format',
			},
			{
				displayName: 'Syllabus Body',
				name: 'syllabus_body',
				type: 'string',
				typeOptions: {
					rows: 4,
				},
				default: '',
				description: 'The syllabus content (supports HTML)',
			},
			{
				displayName: 'Term ID',
				name: 'term_id',
				type: 'string',
				default: '',
				description: 'The term ID for the course',
			},
			{
				displayName: 'Time Zone',
				name: 'time_zone',
				type: 'string',
				default: '',
				description: 'The time zone for the course (e.g., "America/New_York")',
			},
		],
	},

	// ----------------------------------
	//         course: getAll - options
	// ----------------------------------
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Enrollment Role',
				name: 'enrollment_role',
				type: 'string',
				default: '',
				description: 'Filter by custom enrollment role',
			},
			{
				displayName: 'Enrollment Role ID',
				name: 'enrollment_role_id',
				type: 'string',
				default: '',
				description: 'Filter by enrollment role ID',
			},
			{
				displayName: 'Enrollment State',
				name: 'enrollment_state',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Completed', value: 'completed' },
					{ name: 'Invited or Pending', value: 'invited_or_pending' },
				],
				default: 'active',
				description: 'Filter by enrollment state',
			},
			{
				displayName: 'Enrollment Type',
				name: 'enrollment_type',
				type: 'options',
				options: [
					{ name: 'Designer', value: 'designer' },
					{ name: 'Observer', value: 'observer' },
					{ name: 'Student', value: 'student' },
					{ name: 'TA', value: 'ta' },
					{ name: 'Teacher', value: 'teacher' },
				],
				default: 'student',
				description: 'Filter by enrollment type',
			},
			{
				displayName: 'Exclude Blueprint Courses',
				name: 'exclude_blueprint_courses',
				type: 'boolean',
				default: false,
				description: 'Whether to exclude blueprint courses',
			},
			{
				displayName: 'Homeroom',
				name: 'homeroom',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for homeroom courses',
			},
			{
				displayName: 'Include',
				name: 'include',
				type: 'multiOptions',
				options: [
					{ name: 'Banner Image', value: 'banner_image' },
					{ name: 'Concluded', value: 'concluded' },
					{ name: 'Course Image', value: 'course_image' },
					{ name: 'Current Grading Period Scores', value: 'current_grading_period_scores' },
					{ name: 'Favorites', value: 'favorites' },
					{ name: 'Grading Periods', value: 'grading_periods' },
					{ name: 'Needs Grading Count', value: 'needs_grading_count' },
					{ name: 'Observed Users', value: 'observed_users' },
					{ name: 'Permissions', value: 'permissions' },
					{ name: 'Public Description', value: 'public_description' },
					{ name: 'Sections', value: 'sections' },
					{ name: 'Syllabus Body', value: 'syllabus_body' },
					{ name: 'Teachers', value: 'teachers' },
					{ name: 'Term', value: 'term' },
					{ name: 'Total Scores', value: 'total_scores' },
					{ name: 'Total Students', value: 'total_students' },
				],
				default: [],
				description: 'Additional information to include with each course',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'multiOptions',
				options: [
					{ name: 'Available', value: 'available' },
					{ name: 'Completed', value: 'completed' },
					{ name: 'Created', value: 'created' },
					{ name: 'Deleted', value: 'deleted' },
					{ name: 'Unpublished', value: 'unpublished' },
				],
				default: [],
				description: 'Filter by course state',
			},
		],
	},

	// ----------------------------------
	//         course: get - options
	// ----------------------------------
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['get'],
			},
		},
		options: [
			{
				displayName: 'Include',
				name: 'include',
				type: 'multiOptions',
				options: [
					{ name: 'All Courses', value: 'all_courses' },
					{ name: 'Banner Image', value: 'banner_image' },
					{ name: 'Course Image', value: 'course_image' },
					{ name: 'Current Grading Period Scores', value: 'current_grading_period_scores' },
					{ name: 'Grading Periods', value: 'grading_periods' },
					{ name: 'Needs Grading Count', value: 'needs_grading_count' },
					{ name: 'Observed Users', value: 'observed_users' },
					{ name: 'Permissions', value: 'permissions' },
					{ name: 'Public Description', value: 'public_description' },
					{ name: 'Sections', value: 'sections' },
					{ name: 'Syllabus Body', value: 'syllabus_body' },
					{ name: 'Teachers', value: 'teachers' },
					{ name: 'Term', value: 'term' },
					{ name: 'Total Scores', value: 'total_scores' },
					{ name: 'Total Students', value: 'total_students' },
				],
				default: [],
				description: 'Additional information to include with the course',
			},
			{
				displayName: 'Teacher Limit',
				name: 'teacher_limit',
				type: 'number',
				default: 10,
				description: 'Maximum number of teachers to include',
			},
		],
	},

	// ----------------------------------
	//         course: copy - options
	// ----------------------------------
	{
		displayName: 'Source Course ID',
		name: 'sourceCourseId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['copy'],
			},
		},
		description: 'The ID of the source course to copy from',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['copy'],
			},
		},
		options: [
			{
				displayName: 'Except',
				name: 'except',
				type: 'multiOptions',
				options: [
					{ name: 'Announcements', value: 'announcements' },
					{ name: 'Assignment Groups', value: 'assignment_groups' },
					{ name: 'Assignments', value: 'assignments' },
					{ name: 'Attachments', value: 'attachments' },
					{ name: 'Calendar Events', value: 'calendar_events' },
					{ name: 'Discussion Topics', value: 'discussion_topics' },
					{ name: 'Modules', value: 'modules' },
					{ name: 'Quizzes', value: 'quizzes' },
					{ name: 'Rubrics', value: 'rubrics' },
					{ name: 'Wiki Pages', value: 'wiki_pages' },
				],
				default: [],
				description: 'Content types to exclude from the copy',
			},
			{
				displayName: 'Only',
				name: 'only',
				type: 'multiOptions',
				options: [
					{ name: 'Announcements', value: 'announcements' },
					{ name: 'Assignment Groups', value: 'assignment_groups' },
					{ name: 'Assignments', value: 'assignments' },
					{ name: 'Attachments', value: 'attachments' },
					{ name: 'Calendar Events', value: 'calendar_events' },
					{ name: 'Discussion Topics', value: 'discussion_topics' },
					{ name: 'Modules', value: 'modules' },
					{ name: 'Quizzes', value: 'quizzes' },
					{ name: 'Rubrics', value: 'rubrics' },
					{ name: 'Wiki Pages', value: 'wiki_pages' },
				],
				default: [],
				description: 'Content types to include in the copy (if specified, only these are copied)',
			},
		],
	},

	// ----------------------------------
	//         course: listStudents - options
	// ----------------------------------
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: {
			show: {
				resource: ['course'],
				operation: ['listStudents'],
			},
		},
		options: [
			{
				displayName: 'Enrollment State',
				name: 'enrollment_state',
				type: 'multiOptions',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Completed', value: 'completed' },
					{ name: 'Creation Pending', value: 'creation_pending' },
					{ name: 'Deleted', value: 'deleted' },
					{ name: 'Inactive', value: 'inactive' },
					{ name: 'Invited', value: 'invited' },
					{ name: 'Rejected', value: 'rejected' },
				],
				default: ['active'],
				description: 'Filter students by enrollment state',
			},
			{
				displayName: 'Include',
				name: 'include',
				type: 'multiOptions',
				options: [
					{ name: 'Avatar URL', value: 'avatar_url' },
					{ name: 'Bio', value: 'bio' },
					{ name: 'Email', value: 'email' },
					{ name: 'Enrollments', value: 'enrollments' },
					{ name: 'Group IDs', value: 'group_ids' },
					{ name: 'Last Login', value: 'last_login' },
					{ name: 'Locale', value: 'locale' },
					{ name: 'Test Student', value: 'test_student' },
					{ name: 'UUID', value: 'uuid' },
				],
				default: [],
				description: 'Additional information to include with each student',
			},
			{
				displayName: 'Search Term',
				name: 'search_term',
				type: 'string',
				default: '',
				description: 'Search for users by name or login ID',
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				options: [
					{ name: 'Email', value: 'email' },
					{ name: 'Last Login', value: 'last_login' },
					{ name: 'Username', value: 'username' },
				],
				default: 'username',
				description: 'The field to sort students by',
			},
			{
				displayName: 'User IDs',
				name: 'user_ids',
				type: 'string',
				default: '',
				description: 'Comma-separated list of user IDs to filter by',
			},
		],
	},
];
