import type { INodeProperties } from 'n8n-workflow';

export const userObserveeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['userObservee'],
			},
		},
		options: [
			{
				name: 'Add',
				value: 'add',
				description: 'Add an observee to an observer user',
				action: 'Add an observee',
			},
			{
				name: 'Add with Credentials',
				value: 'addWithCredentials',
				description: 'Add an observee using credentials or pairing code',
				action: 'Add an observee with credentials',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get a single observee by ID',
				action: 'Get an observee',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many observees for a user',
				action: 'Get many observees',
			},
			{
				name: 'List Observers',
				value: 'listObservers',
				description: 'Get many observers for a user',
				action: 'Get many observers',
			},
			{
				name: 'Remove',
				value: 'remove',
				description: 'Remove an observee from an observer user',
				action: 'Remove an observee',
			},
		],
		default: 'getAll',
	},
];

export const userObserveeFields: INodeProperties[] = [
	// ----------------------------------
	//         userObservee: all operations
	// ----------------------------------
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['getAll', 'get', 'add', 'addWithCredentials', 'remove', 'listObservers'],
			},
		},
		description: 'The ID of the observer user (for observee operations) or the observed user (for observer operations)',
	},

	// ----------------------------------
	//         userObservee: get, add, remove
	// ----------------------------------
	{
		displayName: 'Observee ID',
		name: 'observeeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['get', 'add', 'remove'],
			},
		},
		description: 'The ID of the user being observed',
	},

	// ----------------------------------
	//         userObservee: addWithCredentials
	// ----------------------------------
	{
		displayName: 'Add Method',
		name: 'addMethod',
		type: 'options',
		required: true,
		options: [
			{
				name: 'Credentials',
				value: 'credentials',
				description: 'Add using observee\'s username and password',
			},
			{
				name: 'Pairing Code',
				value: 'pairingCode',
				description: 'Add using a pairing code generated by the observee',
			},
			{
				name: 'Access Token',
				value: 'accessToken',
				description: 'Add using an access token for the observee',
			},
		],
		default: 'pairingCode',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['addWithCredentials'],
			},
		},
		description: 'Method to use for adding the observee',
	},
	{
		displayName: 'Unique ID',
		name: 'uniqueId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['addWithCredentials'],
				addMethod: ['credentials'],
			},
		},
		description: 'The username/unique ID of the observee',
	},
	{
		displayName: 'Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['addWithCredentials'],
				addMethod: ['credentials'],
			},
		},
		description: 'The password of the observee',
	},
	{
		displayName: 'Pairing Code',
		name: 'pairingCode',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['addWithCredentials'],
				addMethod: ['pairingCode'],
			},
		},
		description: 'The pairing code generated by the student to link an observer',
	},
	{
		displayName: 'Access Token',
		name: 'accessToken',
		type: 'string',
		typeOptions: { password: true },
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['addWithCredentials'],
				addMethod: ['accessToken'],
			},
		},
		description: 'An access token for the observee user',
	},

	// ----------------------------------
	//         userObservee: getAll, get, listObservers - Additional Fields
	// ----------------------------------
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['getAll', 'listObservers'],
			},
		},
		options: [
			{
				displayName: 'Include',
				name: 'include',
				type: 'multiOptions',
				options: [
					{
						name: 'Avatar URL',
						value: 'avatar_url',
						description: 'Include the user\'s avatar URL in the response',
					},
				],
				default: [],
				description: 'Additional data to include in the response',
			},
		],
	},

	// ----------------------------------
	//         userObservee: add, addWithCredentials - Additional Fields
	// ----------------------------------
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['add', 'addWithCredentials'],
			},
		},
		options: [
			{
				displayName: 'Root Account ID',
				name: 'rootAccountId',
				type: 'string',
				default: '',
				description: 'The ID of the root account to scope the operation to',
			},
		],
	},

	// ----------------------------------
	//         userObservee: remove - Additional Fields
	// ----------------------------------
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['userObservee'],
				operation: ['remove'],
			},
		},
		options: [
			{
				displayName: 'Root Account ID',
				name: 'rootAccountId',
				type: 'string',
				default: '',
				description: 'The ID of the root account to scope the removal to',
			},
		],
	},
];
